# Generated by Django 3.1.1 on 2021-04-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id0', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('id1', models.PositiveIntegerField()),
                ('type', models.PositiveIntegerField(verbose_name='Тип ГОСТа')),
                ('gtype', models.PositiveIntegerField()),
                ('status', models.PositiveIntegerField()),
                ('pages', models.PositiveIntegerField()),
                ('num', models.CharField(max_length=128)),
                ('snum', models.PositiveBigIntegerField(blank=True, null=True)),
                ('namer', models.TextField(blank=True, null=True)),
                ('namee', models.TextField(blank=True, null=True)),
                ('obl', models.TextField(blank=True, null=True)),
                ('date0', models.DateField()),
                ('date1', models.DateField(blank=True, null=True)),
                ('date2', models.DateField(blank=True, null=True)),
                ('date3', models.DateField()),
                ('dates', models.TextField(blank=True, null=True)),
                ('rel', models.TextField(blank=True, null=True)),
                ('okp', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Catalog1',
            fields=[
                ('id0', models.AutoField(primary_key=True, serialize=False)),
                ('id1', models.PositiveIntegerField()),
                ('type', models.PositiveIntegerField()),
                ('status', models.PositiveIntegerField()),
                ('num', models.TextField(blank=True, null=True)),
                ('snum', models.PositiveBigIntegerField()),
                ('catid', models.TextField(blank=True, null=True)),
                ('namer', models.TextField(blank=True, null=True)),
                ('obl', models.TextField(blank=True, null=True)),
                ('ogl', models.TextField(blank=True, null=True)),
                ('norm', models.TextField(blank=True, null=True)),
                ('words', models.TextField(blank=True, null=True)),
                ('pack', models.TextField(blank=True, null=True)),
                ('date0', models.DateField(blank=True, null=True)),
                ('date1', models.DateField(blank=True, null=True)),
                ('date2', models.DateField(blank=True, null=True)),
                ('date3', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalog1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Catalog2',
            fields=[
                ('part', models.PositiveIntegerField()),
                ('id0', models.PositiveIntegerField()),
                ('pkey', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('id1', models.PositiveIntegerField()),
                ('stype', models.PositiveIntegerField()),
                ('numru', models.TextField(blank=True, null=True)),
                ('numen', models.TextField(blank=True, null=True)),
                ('snum', models.PositiveBigIntegerField(blank=True, null=True)),
                ('nameru', models.TextField(blank=True, null=True)),
                ('nameen', models.TextField(blank=True, null=True)),
                ('obl', models.TextField(blank=True, null=True)),
                ('ogl', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('pub', models.TextField(blank=True, null=True)),
                ('html', models.PositiveIntegerField()),
                ('gif', models.PositiveIntegerField()),
                ('pages', models.PositiveSmallIntegerField()),
                ('date0', models.DateField()),
                ('date1', models.DateField(blank=True, null=True)),
                ('date2', models.DateField(blank=True, null=True)),
                ('date3', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalog2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Catmenu2',
            fields=[
                ('base', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('id0', models.PositiveIntegerField()),
                ('id1', models.PositiveIntegerField()),
                ('sub', models.PositiveIntegerField()),
                ('nameru', models.TextField()),
                ('nameen', models.TextField(blank=True, null=True)),
                ('comru', models.TextField(blank=True, null=True)),
                ('comen', models.TextField(blank=True, null=True)),
                ('sort', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'catmenu2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Changes',
            fields=[
                ('id0', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('id1', models.PositiveIntegerField()),
                ('type', models.PositiveIntegerField()),
                ('date1', models.DateField(blank=True, null=True)),
                ('date2', models.DateField(blank=True, null=True)),
                ('numr', models.CharField(max_length=128)),
                ('reg', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'changes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Designers',
            fields=[
                ('id0', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('addr', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'designers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doccat',
            fields=[
                ('id0', models.PositiveIntegerField()),
                ('idcat', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'doccat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doccat1',
            fields=[
                ('id0', models.PositiveIntegerField()),
                ('idcat', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'doccat1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doccat2',
            fields=[
                ('part', models.PositiveIntegerField()),
                ('id0', models.PositiveIntegerField()),
                ('idcat', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'doccat2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doclink2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part0', models.PositiveIntegerField()),
                ('id0', models.PositiveIntegerField()),
                ('part1', models.PositiveIntegerField()),
                ('id1', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'doclink2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docrel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typerel', models.PositiveIntegerField()),
                ('part0', models.PositiveIntegerField()),
                ('id0', models.PositiveIntegerField()),
                ('part1', models.PositiveIntegerField()),
                ('id1', models.PositiveIntegerField()),
                ('num', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'docrel2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Org2',
            fields=[
                ('typeorg', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('idorg', models.PositiveIntegerField()),
                ('nameru', models.TextField()),
                ('nameen', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'org2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orgrel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.PositiveIntegerField()),
                ('id0', models.PositiveIntegerField()),
                ('typeorg', models.PositiveIntegerField()),
                ('idorg', models.PositiveIntegerField()),
                ('typerel', models.PositiveIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orgrel2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id0', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'reg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status2',
            fields=[
                ('id0', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('type', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=42)),
                ('typename', models.CharField(max_length=18)),
            ],
            options={
                'db_table': 'status2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id0', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=43)),
                ('count', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Types2',
            fields=[
                ('id0', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nameru', models.CharField(max_length=64)),
                ('nameen', models.CharField(blank=True, max_length=64, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'types2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Windex2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wid', models.PositiveIntegerField()),
                ('part', models.PositiveIntegerField()),
                ('id0', models.PositiveIntegerField()),
                ('density', models.FloatField()),
            ],
            options={
                'db_table': 'windex2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Words2',
            fields=[
                ('wid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=16)),
                ('count', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'words2',
                'managed': False,
            },
        ),
    ]
